"""add category purpose attributes to property

Revision ID: 1625c03ecc6b
Revises: 9917929489af
Create Date: 2026-08-02 00:06:47.248246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1625c03ecc6b'
down_revision = '9917929489af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=False, server_default='property'))
        batch_op.add_column(sa.Column('purpose', sa.String(length=20), nullable=False, server_default='rent'))
        batch_op.add_column(sa.Column('attributes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_column('attributes')
        batch_op.drop_column('purpose')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
