"""approved added to  property

Revision ID: 372b5e5874b1
Revises: 
Create Date: 2023-11-06 07:33:09.284202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '372b5e5874b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_column('approved')

    # ### end Alembic commands ###
