"""add property contact fields

Revision ID: 37900f0ca697
Revises: f92d8e09fc3f
Create Date: 2026-08-11 18:58:34.346264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37900f0ca697'
down_revision = 'f92d8e09fc3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_phone', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('contact_email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('contact_website', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_column('contact_website')
        batch_op.drop_column('contact_email')
        batch_op.drop_column('contact_phone')

    # ### end Alembic commands ###
