"""Changes made to request table

Revision ID: 4e44ad4ef8b0
Revises: b37d55a1bdb7
Create Date: 2023-11-07 13:43:04.385962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e44ad4ef8b0'
down_revision = 'b37d55a1bdb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('property_type', sa.String(length=255), nullable=False))
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('property_type')

    # ### end Alembic commands ###
