"""add room image table

Revision ID: 755e7e6dbad7
Revises: fa65c750ad95
Create Date: 2026-08-11 17:31:38.209200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '755e7e6dbad7'
down_revision = 'fa65c750ad95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('dp', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room_image')
    # ### end Alembic commands ###
