"""add rbac roles and permissions

Revision ID: 76b2c49d5b58
Revises: 6ae5f80f32d4
Create Date: 2026-08-11 20:12:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76b2c49d5b58'
down_revision = '6ae5f80f32d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )

    op.create_table('permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )

    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_role_id', 'role', ['role_id'], ['id'], ondelete='SET NULL')

    # Seed the built-in roles and backfill existing users' role_id.
    conn = op.get_bind()
    conn.execute(sa.text("INSERT INTO role (name, description) VALUES ('user', 'Default role with basic access') ON CONFLICT (name) DO NOTHING"))
    conn.execute(sa.text("INSERT INTO role (name, description) VALUES ('admin', 'Administrator with full access') ON CONFLICT (name) DO NOTHING"))
    conn.execute(sa.text("UPDATE \"user\" SET role_id = (SELECT id FROM role WHERE name = role) WHERE role_id IS NULL"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_role_id', type_='foreignkey')
        batch_op.drop_column('role_id')

    op.drop_table('role_permissions')
    op.drop_table('permission')
    op.drop_table('role')
    # ### end Alembic commands ###
