"""Property available, Property dp

Revision ID: 97f2a4acca9e
Revises: 3e61a906ba24
Create Date: 2023-11-06 17:15:43.220240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97f2a4acca9e'
down_revision = '3e61a906ba24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available', sa.Integer(), nullable=True))

    with op.batch_alter_table('property_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dp', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_image', schema=None) as batch_op:
        batch_op.drop_column('dp')

    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_column('available')

    # ### end Alembic commands ###
