"""Changes made to request colomns

Revision ID: 9917929489af
Revises: 4e44ad4ef8b0
Create Date: 2023-11-07 13:47:28.409500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9917929489af'
down_revision = '4e44ad4ef8b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bedrooms', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bathrooms', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('area', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('year_built', sa.Integer(), nullable=True))
        batch_op.drop_column('rooms')
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('rooms', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('year_built')
        batch_op.drop_column('area')
        batch_op.drop_column('country')
        batch_op.drop_column('bathrooms')
        batch_op.drop_column('bedrooms')

    # ### end Alembic commands ###
